### ISSUE TITLE
Does not work with hexo-renderer-jade

### ISSUE THREAD

**Issue by akfish** [hexojs/hexo-inject#1]
Originated from akfish/hexo-math#26.

The theme used in that issue requires hexo-renderer-jade to render. In such configuration, the `after_render:html` is not fired with full HTML source, causing hexo-inject not being able to inject scripts.

Further investigation is required to pin point the source of this issue.

**Comment by ngloom** [comment]
come into this problem today,  
hope it fixed soon,
great work &  thanks very much !

**Comment by kchen0x** [comment]
+1

**Comment by shinux** [comment]
Also, maybe there are conflicts with `"hexo-renderer-pug": "0.0.5"` ?

**Comment by yoshinorin** [comment]
@ngloom @kchen0x @shinux 
This plugin has been deprecated and no longer compatible with current version of Hexo. 

Hexo has built-in injector supports since Hexo 5.0.0.
Please read [`Injector` API documents](https://hexo.io/api/injector) for more details.

Thank you :)
