### ISSUE TITLE
Can you please add example with script helper

### ISSUE THREAD

**Issue by iamchathu** [hexojs/hexo-inject#2]
Can you please add an example using script helper mentioned in the readme to how to inject a script.

I'm working on a tag plugin which needs to have js script inject to head.

Thank you.

**Comment by yoshinorin** [comment]
@iamchathu 
This plugin has been deprecated and no longer compatible with current version of Hexo. 

Hexo has built-in injector supports since Hexo 5.0.0.
Please read [`Injector` API documents](https://hexo.io/api/injector) for more details.

Thank you :)
