### ISSUE TITLE
hexo inject body begin doesn't work with default theme

### ISSUE THREAD

**Issue by iamchathu** [hexojs/hexo-inject#3]
I have created fresh init for a new blog which comes with the default theme. I used

```js
hexo.extend.filter.register('inject_ready', (inject) => {
  // Inject fb sdk at body_begin
  inject.raw('body_begin', 'inject content test');

});
```

In my plugin and this doesn't inject raw content it specified to body begin.

**Comment by glazec** [comment]
add hexo-inject into blog dependency. Then it will work

**Comment by yoshinorin** [comment]
@iamchathu @glazec 
This plugin has been deprecated and no longer compatible with current version of Hexo. 

Hexo has built-in injector supports since Hexo 5.0.0.
Please read [`Injector` API documents](https://hexo.io/api/injector) for more details.

Thank you :)
