### ISSUE TITLE
error:  Incomplete document

### ISSUE THREAD

**Issue by xu-song** [hexojs/hexo-inject#4]
The following error occurs while running `hexo s --debug`
```
02:48:48.728 DEBUG [hexo-inject] SKIP: undefined
02:48:48.728 DEBUG Incomplete document
Error: Incomplete document
    at Inject._transform (/home/user/xs/web/blog-dev/node_modules/hexo-inject/lib/mixin/transform.js:29:34)
    at Hexo.tryCatcher (/home/user/xs/web/blog-dev/node_modules/bluebird/js/release/util.js:16:23)

```

**Comment by yuanzi222** [comment]
I also encountered this problem

**Comment by SukkaW** [comment]
@xu-song @yuanzi222 hexo-inject is no longer maintained and should be considered as deprecated.

**Comment by Zhou-Bill** [comment]
how to solve

**Comment by yoshinorin** [comment]
@xu-song @yuanzi222 @Zhou-Bill 
This plugin has been deprecated and no longer compatible with current version of Hexo. 

Hexo has built-in injector supports since Hexo 5.0.0.
Please read [`Injector` API documents](https://hexo.io/api/injector) for more details.

Thank you :)
