### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by jerryc127** [hexojs/hexo-inject#70]
I install it 
and then hexo clean && hexo g && hexo s
but the website some error

我安裝了這個插件
沒有進行其他操作。然後hexo clean && hexo g && hexo s
打開F12發現報錯
它在我的head script裏(只有這一個有被插入)插入了 `<!-- hexo-inject:begin --><!-- hexo-inject:end -->`,
![image](https://user-images.githubusercontent.com/16351105/72359864-088f8900-372a-11ea-8bc3-f63ed1956d7e.png)
![image](https://user-images.githubusercontent.com/16351105/72359925-265cee00-372a-11ea-835c-be869a486b05.png)

script裏的内容是寫在pug上的。。不是通過js那些插入

**Comment by SukkaW** [comment]
This plugin should be considered as deprecated. In coming new Hexo 4.3.0 will have built-in injector support.

**Comment by yoshinorin** [comment]
@jerryc127 
This plugin has been deprecated and no longer compatible with current version of Hexo. 

Hexo has built-in injector supports since Hexo 5.0.0.
Please read [`Injector` API documents](https://hexo.io/api/injector) for more details.

Thank you :)
